const API_BASE_URL = "http://163.227.92.122:4032/"

const DISABLE_API_LOGS = false

// const API_ROUTES = {
//     login: 'userService/auth/login',
//     signup: 'userService/auth/start',
//     verifyOtp: 'userService/auth/verify',
//     resendOtp: 'userService/auth/resend-otp',
//     createPassword: 'userService/auth/password',
//     addPersonalDetails: 'service_seeker/auth/details',
//     addVerificationDoc: 'service_seeker/auth/upload-verification-docs',
//     addressCreate:"service_seeker/address/create",
//     resetPassword: 'userService/auth/reset/start',
//     verifyResetPassword: 'userService/auth/reset/verify',
//     createNewPassword: 'userService/auth/reset/confirm',
//     getUserDetails: 'userService/auth/get_user',
//     uploadProfileImage: 'userService/auth/upload-profile-photo',
//     uploadSeekerProfilePhoto: 'service_seeker/auth/upload-seeker-profile-photo',
//     uploadProviderProfilePhoto: 'service_provider/auth/provider/upload-profile-photo',
//     getHomeData: "home_module/home",
//     getAllPlans: "userService/auth/plans/all",
//     getPlanDetails: "userService/auth/plans",
//     uploadDocuments: 'userService/auth/provider/upload-documents',
//     addYearsOfExperience: 'userService/auth/experience',
//     onSelectPlan: "userService/auth/select-plan",
//     allCategories: "home_module/all_categories",
//     uploadServiceRequestImage: "service_request/upload-job-file",
//     editProfile: "profile_module/profile",
//     onServiceRequest: "service_request/service-requests",
//     ratingAndReviews: "elderly_profile/profile?section=ratings_reviews",
//     // deleteProfile: "elderly_profile/profile?section=my_profile",
//     deleteProfile: "userService/auth/delete-profile",
//     getAllRequests: "service_confirmation/service_accept/get_services",
//     onSelectedCategories: "userService/auth/select-categories",
//     onSelectedServices: "userService/auth/select-sub-categories",
//     getServiceDetails: "service_confirmation/service_accept/get_service",
//     getFavoriteProfessionals: "service_confirmation/favorite-provider/fetch",
//     onSendCategoryIds: "userService/auth/select-provider-services",
//     fetchTransactions: "profile_module/user_profile",
//     getProfessionalAllServices: "quote_request/open-services",
//     getProfessionalServiceDetails: "quote_request/service-info",
//     sendQuoteRequest: "quote_request/quoterequest",
//     fileUploadProfessionalServices: "quote_request/upload-job-file",
//     uploadProviderJobFiles: "profile_module/upload-files",
//     getProviderUserDetails: "service_confirmation/service_accept/provider_user",
//     getQuateList: "quote_accept/service-provider/quotes",
//     addFavoriteProfessional: "service_confirmation/favorite-provider/add",
//     removeFavoriteProfessional: "service_confirmation/favorite-provider/remove",
//     onServiceReject: "service_confirmation/service_accept/reject_quote",
//     getServiceAmount: "service_confirmation/service_accept/amounts",
//     onAcceptService: "service_confirmation/service_accept/accept_quote",
//     getServicePaymentDetails: "service_confirmation/service_accept/payment-details",
//     otherUserProfile: "service_confirmation/service_accept/user",
//     confirmPayment: "service_confirmation/service_accept/confirm-payment",
//     onWriteReview: "service_confirmation/ratings/submit",
//     getCancelServiceDetails: "service_request/get-payment",
//     onCancelService: "service_request/cancel",
//     getAllService: "userService/provider-services",
//     getTsakDetails: "quote_accept/service-provider",
//     getRefreshToken: "userService/auth/refresh-token",
//     subscriptionPayment: "subscription_and_payment/subscription/select-plan",
//     getTaskStatus: "quote_accept/service-provider/task-status",
//     getEarningsDashboard: "subscription_and_payment/wallet-withdraw/dashboard",
//     getWithdrawHistory: "subscription_and_payment/wallet-withdraw/user-withdraw",
//     getMyWalletBalance: "subscription_and_payment/wallet-withdraw/my-wallet",
//     removeService: "userService/remove-service",
//     getProviderTransactions: "subscription_and_payment/wallet-withdraw/provider-transactions",
//     onProceedOutOfService: "quote_accept/proceed-out-for-service",
//     onSelectedCategoriesNonProfessional: "subscription_and_payment/categories/purchase",
//     getSubscriptionPlanDetails: "userService/auth/plans",
//     getApplicationStatus: "userService/verify/profile",
//     onProceedFurther: "quote_accept/procced_futher",
//     onVerifySecurityCode: "quote_accept/provider/confirm_start",
//     getRenegotiationDetails: "quote_accept/service-provider/renegotiation",
//     onProcessRenegotiation: 'quote_accept',
//     onMarkAsCompleted: 'quote_accept/mark-service-completed',
//     onValidateSecurityCode: 'quote_accept/validate-service-code',
//     onNotification: "userService/devices-token/register-token",
//     getNotifications: "userService/notifications/get",
//     getSubscriptionData: "subscription_and_payment/subscription/success-data",
//     onConfirmStart: "service_confirmation/service_accept/elder/confirm_start",
//     onNotArrived: "service_confirmation/service_accept/elder/not_arrived",
//     onRenegotiationAccept: "service_confirmation/service_accept/renegotiation/accept",
//     onRenegotiationDecline: "service_confirmation/service_accept/renegotiation/decline",
//     getSavedAddresses: "service_request/addresses/get_list",
//     onCreateAddress: "service_request/addresses/create",
//     onUpdateAddress: "service_request/addresses",
//     onPaymanWithdrawal: "subscription_and_payment/wallet-withdraw/create",
//     createNegotiationChat: "service_confirmation/service_accept/create_negotiation",
//     getReviewData: "service_confirmation/ratings/service"

// }

const API_ROUTES = {
    auth: {
        login: 'userService/auth/login',
        signup: 'userService/auth/start',
        verifyOtp: 'userService/auth/verify',
        resendOtp: 'userService/auth/resend-otp',
        createPassword: 'userService/auth/password',
        addressCreate: "service_seeker/address/create",
        resetPassword: 'userService/auth/reset/start',
        verifyResetPassword: 'userService/auth/reset/verify',
        createNewPassword: 'userService/auth/reset/confirm',
        logout: "userService/auth/logout",
    },
    common:{
         getAllCategories:"service_provider/auth/all_categories",
         updateSelectedCategories:'service_provider/auth/provider/categories'
    },
    service_seeker: {
        addPersonalDetails: 'service_seeker/auth/details',
        uploadSeekerProfilePhoto: 'service_seeker/auth/upload-seeker-profile-photo',
        addressCreate: "service_seeker/address/create",
        addressList: "service_seeker/address/list",
        addressUpdate: "service_seeker/address/549cbc2a-cf44-4422-aace-19a7a6406966",
        addressDelete: "service_seeker/address/e8db5f7e-32cd-45f8-8795-2c21ac1e714b",
        addVerificationDoc: 'service_seeker/auth/upload-verification-docs',
        seekerProfile:'service_seeker/auth/me',
        homeServices:'service_seeker/seeker/home',
        edit_profile:'service_seeker/auth/details'
    },
    service_provider: {
        addProviderPersonalDetails: "service_provider/auth/provider/details",
        addProviderVerificationDoc: "service_provider/auth/provider/upload-verification-docs",
        addProviderVerificationDetails: "service_provider/auth/provider/verification",
        uploadProviderProfilePhoto: "service_provider/auth/provider/upload-profile-photo",
        providerAddressCreate: "service_provider/provider/address/create",
        providerAddressList: "service_provider/provider/address/list",
        providerAddressUpdate: "service_provider/provider/address/ec3cdece-1d83-4494-9a97-d0aaca521598", //
        providerAddressDelete: "service_provider/provider/address/61ce9b5d-ef6a-46f6-9b11-209bda69a419", //
        providerProfile:"service_provider/auth/provider/me"
    }
}

export { API_ROUTES, API_BASE_URL, DISABLE_API_LOGS }